[metadata]
name = edx-data-exporter
description_file = README.md
python_requires = >=3.12

[entry_points]
console_scripts =
    exporter = exporter.main:main
    exporter-properties = exporter.properties:main
    exporter-check = exporter.check:main
    course-exporter = exporter.course_export:main
